// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking.API.Data;

#nullable disable

namespace Parking.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parking.API.Models.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OccupiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OccupiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleSize")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = false,
                            VehicleSize = 0,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            VehicleSize = 1,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            VehicleSize = 2,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = true,
                            VehicleSize = 0,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 5,
                            IsOccupied = true,
                            VehicleSize = 1,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 6,
                            IsOccupied = false,
                            VehicleSize = 2,
                            ZoneId = 3
                        });
                });

            modelBuilder.Entity("Parking.API.Models.Entities.ParkingZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkingZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            Name = "Zone A",
                            VehicleSize = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Name = "Zone B",
                            VehicleSize = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            Name = "Zone C",
                            VehicleSize = 2
                        });
                });

            modelBuilder.Entity("Parking.API.Models.Entities.ParkingSpot", b =>
                {
                    b.HasOne("Parking.API.Models.Entities.ParkingZone", "Zone")
                        .WithMany("ParkingSpots")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Parking.API.Models.Entities.ParkingZone", b =>
                {
                    b.Navigation("ParkingSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
