version: '3.4'

services:
  vehicledb:
    image: postgres

  parkingdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  vehicle.api:
    image: ${DOCKER_REGISTRY-}vehicleapi
    build:
      context: .
      dockerfile: Services/Vehicle/Vehicle.API/Dockerfile

  parking.api:
    image: ${DOCKER_REGISTRY-}parkingapi
    build:
      context: .
      dockerfile: Services/Parking/Parking.API/Dockerfile

  pricing.api:
    image: ${DOCKER_REGISTRY-}pricingapi
    build:
      context: .
      dockerfile: Services/Pricing/Pricing.API/Dockerfile

volumes:
  postgres_vehicle:
  postgres_parking:

